server:
  port: 8091

# 数据库配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:13306/zhizhi?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    pool-name: Retail_HikariCP
    minimum-idle: 15 #最小空闲连接数量
    idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
    maximum-pool-size: 25 #连接池最大连接数，默认是10
    auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
    max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
    connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
    connection-test-query: SELECT 1
  type: com.zaxxer.hikari.HikariDataSource

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 数据库配置 - sharding-jdbc 分库分表
#spring:
#  datasource:
#    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
#    url: jdbc:shardingsphere:classpath:sharding/sharding-jdbc-dev.yaml

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml
  map-underscore-to-camel-case: true #字段驼峰

# Sa-Token配置
sa-token:
  # token前缀
  # Token前缀 与 Token值 之间必须有一个空格。
  # 一旦配置了 Token前缀，则前端提交 Token 时，必须带有前缀，否则会导致框架无法读取 Token。
  # 由于Cookie中无法存储空格字符，也就意味配置 Token 前缀后，Cookie 鉴权方式将会失效，此时只能将 Token 提交到header里进行传输
#  token-prefix: Bearer
  # token 名称 (同时也是cookie名称)
  token-name: X-Token
  # 不设置前缀会出现检验时未登录的情况
#  token-prefix: Bearer
  # token 有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token 临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 配置 Sa-Token 单独使用的 Redis 连接
  alone-redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间
    timeout: 6s

# Redis
redis:
  sdk:
    config:
      host: 127.0.0.1
      port: 6379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

minio:
  endpoint: http://localhost:9000
  accessKey: your-access-key
  secretKey: your-secret-key
  bucketName: your-bucket-name

# Dubbo
#dubbo:
#  application:
#    name: zhizhi
#    version: 1.0.0
#  registry:
#    id: nacos-registry
#    address: nacos://127.0.0.1:8848
#  protocol:
#    name: dubbo
#    port: -1
#  scan:
#    base-packages: cn.xu.api

# RocketMQ 配置，在docs/dev-ops下，有创建 xfg-group 脚本，也有场景mq消息的脚本
#rocketmq:
#  name-server: 127.0.0.1:9876
#  consumer:
#    group: xfg-group
#    # 一次拉取消息最大值，注意是拉取消息的最大值而非消费最大值
#    pull-batch-size: 10
#  producer:
#    # 发送同一类消息的设置为同一个group，保证唯一
#    group: xfg-group
#    # 发送消息超时时间，默认3000
#    sendMessageTimeout: 10000
#    # 发送消息失败重试次数，默认2
#    retryTimesWhenSendFailed: 2
#    # 异步消息重试此处，默认2
#    retryTimesWhenSendAsyncFailed: 2
#    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
#    maxMessageSize: 4096
#    # 压缩消息阈值，默认4k(1024 * 4)
#    compressMessageBodyThreshold: 4096
#    # 是否在内部发送失败时重试另一个broker，默认false
#    retryNextServer: false

# xxl-job https://www.xuxueli.com/xxl-job/#%E6%AD%A5%E9%AA%A4%E4%B8%80%EF%BC%9A%E8%B0%83%E5%BA%A6%E4%B8%AD%E5%BF%83%E9%85%8D%E7%BD%AE%EF%BC%9A
#xxl:
#  job:
#    # 验证信息 官网Bug https://github.com/xuxueli/xxl-job/issues/1951
#    accessToken: default_token
#    # 注册地址
#    admin:
#      addresses: http://localhost:9090/xxl-job-admin
#    # 注册执行器
#    executor:
#      #  执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
#      address:
#      appname: xxl-job-executor-sample
#      # 执行器IP 配置为本机IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
#      ip:
#      # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
#      port: 9999
#      # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
#      logpath: ./data/applogs/xxl-job/jobhandler
#      # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
#      logretentiondays: 30

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml